apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
name: nginx-service
labels:
  app: nginx-service
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: nginx
  tier: nginx
type: LoadBalancer
